# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
    ]
